# Generated by Django 5.0.4 on 2024-04-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
